// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vytal-panels/CommunityDashboard.tsx": () => import("../components/mockups/vytal-panels/CommunityDashboard.tsx"),
  "./components/mockups/vytal-panels/PartnerDashboard.tsx": () => import("../components/mockups/vytal-panels/PartnerDashboard.tsx")
};
